name       : mpd
version    : 0.20.6
release    : 15
homepage   : http://www.musicpd.org/
source     :
    - http://www.musicpd.org/download/mpd/0.20/mpd-0.20.6.tar.xz : f4055e1189e5cc00e83706b2e0b5ead924ced0303e073d7802ee9f9a8eba4b47
license    : GPL-2.0
component  : multimedia.audio
summary    : MPD is a flexible, powerful, server-side application for playing music.
description: Music Player Daemon (MPD) is a flexible, powerful, server-side application
    for playing music. Through plugins and libraries it can play a variety of sound
    files while being controlled by its network protocol.
builddeps  :
    - pkgconfig(avahi-client)
    - pkgconfig(icu-io)
    - pkgconfig(libavcodec)
    - pkgconfig(libcurl)
    - pkgconfig(libmodplug)
    - pkgconfig(libpulse)
    - pkgconfig(shout)
    - pkgconfig(sqlite3)
    - libboost-devel
setup      : |
    %configure --disable-static --enable-pulse --enable-lastfm --with-systemdsystemunitdir=%libdir%/systemd/system
build      : |
    %make
install    : |
    %make_install
