name       : mpd
version    : 0.21.24
release    : 60
homepage   : https://www.musicpd.org
source     :
    - https://github.com/MusicPlayerDaemon/MPD/archive/v0.21.24.tar.gz : 0d4072da64676af5c501fa9f2ab813996f7eae5edeb1e1469f64e385188e211d
license    : GPL-2.0-or-later
component  : multimedia.audio
summary    : MPD is a flexible, powerful, server-side application for playing music
description: |
    Music Player Daemon (MPD) is a flexible, powerful, server-side application for playing music.
    Through plugins and libraries it can play a variety of sound files while being controlled by its
    network protocol.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(avahi-client)
    - pkgconfig(cppunit) # check
    - pkgconfig(flac)
    - pkgconfig(icu-io)
    - pkgconfig(id3tag)
    - pkgconfig(libavcodec)
    - pkgconfig(libcurl)
    - pkgconfig(libmodplug)
    - pkgconfig(libmpdclient)
    - pkgconfig(libmpg123)
    - pkgconfig(libpulse)
    - pkgconfig(libupnp)
    - pkgconfig(opus)
    - pkgconfig(samplerate)
    - pkgconfig(shout)
    - pkgconfig(smbclient)
    - pkgconfig(soxr)
    - pkgconfig(sqlite3)
    - bzip2-devel
    - faad-devel
    - lame-devel
    - libboost-devel
    - libgcrypt-devel
    - libmad-devel
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -Dm00644 doc/mpdconf.example $installdir/usr/share/doc/mpd/mpd.conf
check      : |
    %ninja_check
