name       : mpd
version    : 0.19.10
release    : 2
homepage   : http://www.musicpd.org/
source     :
    - http://www.musicpd.org/download/mpd/0.19/mpd-0.19.10.tar.xz : c386eb3d22f98dc993b5ae3c272f969aa7763713483c6800040ebf1791b15851
license    : GPL-2.0
summary    : MPD is a flexible, powerful, server-side application for playing music.
builddeps  :
    - pkgconfig(libmodplug)
    - ffmpeg
    - libshout-devel
    - libmad-devel
    - curl
    - sqlite3
    - avahi
    - libid3tag-devel
    - pulseaudio-devel
    - libboost-devel
    - libicu-devel
description: |
   	Music Player Daemon (MPD) is a flexible, powerful, server-side application for playing music. Through plugins and libraries it can play a variety of sound files while being controlled by its network protocol.
setup      : |
    export BOOST_LIB_SUFFIX=""
    ./configure --prefix=/usr --build=x86_64-solus-linux --libdir=/usr/lib64 --mandir=/usr/share/man --infodir=/usr/share/man --datadir=/usr/share/ --docdir=/usr/share/doc/mpd --sysconfdir=/etc --localstatedir=/var --libexecdir=/usr/lib64/mpd --enable-pulse --enable-lastfm
build      : |
    %make
install    : |
    %make_install
