name       : mpd
version    : 0.20.11
release    : 24
homepage   : http://www.musicpd.org/
source     :
    - http://www.musicpd.org/download/mpd/0.20/mpd-0.20.11.tar.xz : e9227d9daf32a63d6f34bf2ea18b3179b4a383e9d2b49d548702a37451e514bc
license    : GPL-2.0
component  : multimedia.audio
summary    : MPD is a flexible, powerful, server-side application for playing music.
description: |
    Music Player Daemon (MPD) is a flexible, powerful, server-side application for playing music.
    Through plugins and libraries it can play a variety of sound files while being controlled by its
    network protocol.
builddeps  :
    - pkgconfig(avahi-client)
    - pkgconfig(flac)
    - pkgconfig(icu-io)
    - pkgconfig(id3tag)
    - pkgconfig(libavcodec)
    - pkgconfig(libcurl)
    - pkgconfig(libmodplug)
    - pkgconfig(libmpdclient)
    - pkgconfig(libpulse)
    - pkgconfig(libupnp)
    - pkgconfig(opus)
    - pkgconfig(samplerate)
    - pkgconfig(smbclient)
    - pkgconfig(shout)
    - pkgconfig(sqlite3)
    - bzip2-devel
    - libboost-devel
    - libmad-devel
setup      : |
    %configure --disable-static \
        --enable-database \
        --enable-lastfm \
        --enable-pulse \
        --with-systemdsystemunitdir=%libdir%/systemd/system \
        --with-systemduserunitdir=%libdir%/systemd/user
build      : |
    %make
install    : |
    %make_install
