name       : mpd
version    : 0.20.14
release    : 28
homepage   : http://www.musicpd.org/
source     :
    - https://www.musicpd.org/download/mpd/0.20/mpd-0.20.14.tar.xz : 7d59afa1e7aabe5f7ad2d66eb274b0d54568b4110a783dfe8e74bd0f94e3f781
license    : GPL-2.0
component  : multimedia.audio
summary    : MPD is a flexible, powerful, server-side application for playing music
description: |
    Music Player Daemon (MPD) is a flexible, powerful, server-side application for playing music.
    Through plugins and libraries it can play a variety of sound files while being controlled by its
    network protocol.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(avahi-client)
    - pkgconfig(cppunit) # check
    - pkgconfig(flac)
    - pkgconfig(icu-io)
    - pkgconfig(id3tag)
    - pkgconfig(libavcodec)
    - pkgconfig(libcurl)
    - pkgconfig(libmodplug)
    - pkgconfig(libmpdclient)
    - pkgconfig(libpulse)
    - pkgconfig(libupnp)
    - pkgconfig(opus)
    - pkgconfig(samplerate)
    - pkgconfig(smbclient)
    - pkgconfig(shout)
    - pkgconfig(sqlite3)
    - bzip2-devel
    - libboost-devel
    - libmad-devel
setup      : |
    %configure --enable-database \
        --enable-pulse \
        --enable-test \
        --with-systemdsystemunitdir=%libdir%/systemd/system \
        --with-systemduserunitdir=%libdir%/systemd/user
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
