name       : mpd
version    : 0.23.10
release    : 80
homepage   : https://www.musicpd.org
source     :
    - https://github.com/MusicPlayerDaemon/MPD/archive/refs/tags/v0.23.10.tar.gz : 33285ae583d6edcfee770f9fb46168567c4019c7d48533a9cb726305d6b5e6b8
license    : GPL-2.0-or-later
component  : multimedia.audio
summary    : MPD is a flexible, powerful, server-side application for playing music
description: |
    Music Player Daemon (MPD) is a flexible, powerful, server-side application for playing music. Through plugins and libraries it can play a variety of sound files while being controlled by its network protocol.
builddeps  :
    - pkgconfig(ao)
    - pkgconfig(alsa)
    - pkgconfig(audiofile)
    - pkgconfig(avahi-client)
    - pkgconfig(bzip2)
    - pkgconfig(cppunit) # check
    - pkgconfig(faad2)
    - pkgconfig(flac)
    - pkgconfig(fluidsynth)
    - pkgconfig(fmt)
    - pkgconfig(icu-io)
    - pkgconfig(id3tag)
    - pkgconfig(jack)
    - pkgconfig(libavcodec)
    - pkgconfig(libcdio_paranoia)
    - pkgconfig(libchromaprint)
    - pkgconfig(libcurl)
    - pkgconfig(libgcrypt)
    - pkgconfig(libmikmod)
    - pkgconfig(libmodplug)
    - pkgconfig(libmpdclient)
    - pkgconfig(libmpg123)
    - pkgconfig(libmms)
    - pkgconfig(libnfs)
    - pkgconfig(libopenmpt)
    - pkgconfig(libpipewire-0.3)
    - pkgconfig(libpulse)
    - pkgconfig(libupnp)
    - pkgconfig(liburing)
    - pkgconfig(mad)
    - pkgconfig(openal)
    - pkgconfig(opus)
    - pkgconfig(samplerate)
    - pkgconfig(shout)
    - pkgconfig(smbclient)
    - pkgconfig(sndio)
    - pkgconfig(soxr)
    - pkgconfig(sqlite3)
    - pkgconfig(wavpack)
    - pkgconfig(wildmidi)
    - pkgconfig(yajl)
    - pkgconfig(zziplib)
    - lame-devel
    - libboost-devel
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -Dm00644 doc/mpdconf.example $installdir/usr/share/doc/mpd/mpd.conf
check      : |
    %ninja_check
