name       : mpd
version    : 0.20.9
release    : 19
homepage   : http://www.musicpd.org/
source     :
    - http://www.musicpd.org/download/mpd/0.20/mpd-0.20.9.tar.xz : cd77a2869e32354b004cc6b34fcb0bee56114caa2d9ed862aaa8071441e34eb7
license    : GPL-2.0
component  : multimedia.audio
summary    : MPD is a flexible, powerful, server-side application for playing music.
description: |
    Music Player Daemon (MPD) is a flexible, powerful, server-side application for playing music.
    Through plugins and libraries it can play a variety of sound files while being controlled by its
    network protocol.
builddeps  :
    - pkgconfig(avahi-client)
    - pkgconfig(icu-io)
    - pkgconfig(libavcodec)
    - pkgconfig(libcurl)
    - pkgconfig(libmodplug)
    - pkgconfig(libpulse)
    - pkgconfig(shout)
    - pkgconfig(sqlite3)
    - bzip2-devel
    - libboost-devel
setup      : |
    %configure --disable-static --enable-pulse --enable-lastfm --with-systemdsystemunitdir=%libdir%/systemd/system --with-systemduserunitdir=%libdir%/systemd/user
build      : |
    %make
install    : |
    %make_install
